name: study_mcq
description: Study MCQ App
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  google_mobile_ads: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/StudyMCQ.html
    - assets/ibps_data.js
    - assets/jee_data.js
    - assets/neet_data.js
    - assets/nism_data.js
    - assets/railwayrrb_data.js
    - assets/upsc_data.js
    - assets/maths_data_10.js
    - assets/science_data_10.js
    - assets/commerce12_accounts.js
    - assets/science12_physics.js
    - assets/science12_chemistry.js
    - assets/commerce12_economics.js
    - assets/commerce12_ocm.js
    - assets/history_data_10.js
    - assets/science12_biology.js
    - assets/arts12_history.js
    - assets/arts12_sociology.js
    - assets/arts12_psychology.js
    - assets/arts12_geography.js
    - assets/arts12_polsci.js
    - assets/arts12_economics.js
    - assets/science12_maths.js
    - assets/geo10_marathi.js
    - assets/History10_Marathi.js
    - assets/science10_marathi.js
    - assets/ssc10_maths.js
    - assets/StudyBanner.png
    - assets/StudyLogo.png
