name: study_mcq
description: Study MCQ App
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  google_mobile_ads: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/StudyMCQ.html
    - assets/ibps_data.js
    - assets/jee_data.js
    - assets/neet_data.js
    - assets/nism_data.js
    - assets/railwayrrb_data.js
    - assets/upsc_data.js
    - assets/maths_data_10.js
    - assets/science_data_10.js
    - assets/history_data_10.js
    - assets/StudyBanner.png
    - assets/StudyLogo.png
